spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://docker:5432/migration_test_db
    username: migrationtestdbuser
    password: migrationtestdbpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false