ALTER TABLE ONLY books
ADD CONSTRAINT books_pkey PRIMARY KEY (id);

CREATE SEQUENCE books_seq
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

ALTER TABLE books_seq OWNER TO migrationtestdbuser;